[package]
name = "goto"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
google-calendar3 = "6.0.0"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
